pipeline {
    agent any
	environment {
		DOCKER_HUB = "udipoc"
        VERSION = "0.0.1-SNAPSHOT"
	}
    tools {
        nodejs 'node'
    }

    stages{
        stage('SCM Clone'){
            steps{
                git branch: '1.1.3-develop', url: 'https://github.com/ICTASL/mosip-ref-impl.git'
            }
        }
        stage('Init'){
            steps{
                dir('pre-registration-ui') { 
				    sh 'npm install'
                }
            }
        }
        stage('Build'){
            steps{
                dir('pre-registration-ui') { 
				    sh "npm run ng build --prod --base-href"
                }
			}
        }
        stage('SonarQube-Analysis'){
            environment{
                scannerHome = tool 'sonar_scanner'
            }
            steps{
				    withSonarQubeEnv('sonarqube'){
				        sh '${scannerHome}/bin/sonar-scanner'
				    }
				    
				    timeout(time: 15, unit: 'MINUTES'){
				        waitForQualityGate abortPipeline: true
				    }
                }
        }
        
		stage('Build-DockerImage') {
		  steps{
			dir('pre-registration-ui') { 
				sh 'docker build . -t ${DOCKER_HUB}/pre-registration-ui:${VERSION} '
			}
		  }
		}
		stage('Push-DockerImage') {
		  steps {
		      withDockerRegistry(credentialsId: 'udipoc', url: '') {
		          sh 'docker push ${DOCKER_HUB}/pre-registration-ui:${VERSION}'
		      }
		  }
        }
        
        /**
        stage('Deploy-DockerImage'){
            steps{
                withDockerRegistry(credentialsId: 'udipoc', url: '') {
		          ansiblePlaybook credentialsId: 'dev_test_key', disableHostKeyChecking: true, installation: 'ansible', inventory: '/home/uploads/dev.inv', playbook: '/home/uploads/deploy-pre-registration-ui.yml'
		      }
            }
        }**/
    }
}